# Generated by Django 6.0.5 on 2026-05-24 14:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('region', models.CharField(blank=True, help_text='ISO country, blank = global', max_length=2)),
                ('fuel_type', models.CharField(blank=True, help_text='diesel, natural_gas, ...', max_length=40)),
                ('factor_value', models.DecimalField(decimal_places=6, max_digits=14)),
                ('factor_unit', models.CharField(help_text='e.g. kgCO2e/L, kgCO2e/kWh, kgCO2e/EUR', max_length=40)),
                ('currency', models.CharField(blank=True, help_text='set for spend-based factors', max_length=3)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('source', models.CharField(help_text="provenance, e.g. 'DEFRA 2024'", max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Source-native code, e.g. SAP plant 'DE01'", max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(help_text='ISO-3166 alpha-2, drives grid factor', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('admin', 'Admin')], default='analyst', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='ingest.organization')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('category', models.CharField(choices=[('stationary_combustion', 'Stationary combustion'), ('mobile_combustion', 'Mobile combustion'), ('purchased_electricity', 'Purchased electricity'), ('purchased_goods', 'Purchased goods & services'), ('business_travel_air', 'Business travel — air'), ('business_travel_hotel', 'Business travel — hotel'), ('business_travel_ground', 'Business travel — ground')], max_length=40)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, help_text='canonical unit', max_length=20)),
                ('original_quantity', models.CharField(blank=True, help_text='verbatim from raw', max_length=60)),
                ('original_unit', models.CharField(blank=True, help_text='verbatim from raw', max_length=40)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, help_text='kept native; not month-aligned', null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=3, help_text='provisional until status=locked', max_digits=18, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked (audit-sealed)')], default='pending', max_length=12)),
                ('flags', models.JSONField(blank=True, default=list, help_text="e.g. ['MISSING_UNIT','OUTLIER','POSSIBLE_DUPLICATE']")),
                ('edited_at', models.DateTimeField(blank=True, help_text='null = untouched by a human', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.emissionfactor')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.facility')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='edit | approve | reject | lock | ingest', max_length=40)),
                ('field', models.CharField(blank=True, max_length=60)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingest.activityrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP (fuel & procurement)'), ('UTILITY', 'Utility (electricity)'), ('TRAVEL', 'Corporate travel')], max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='processing', max_length=12)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_ok', models.IntegerField(default=0)),
                ('rows_flagged', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingest.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='ingest.importbatch'),
        ),
        migrations.AddField(
            model_name='facility',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='ingest.organization'),
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='ingest.organization'),
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.IntegerField(help_text='1-based position in the source file')),
                ('payload', models.JSONField(help_text='original row, original headers, original units, verbatim')),
                ('parse_error', models.TextField(blank=True, help_text='set when the line could not be normalized')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingest.importbatch')),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='ingest.rawrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('org', 'code')},
        ),
    ]
